# Pokemon App Helm Chart
apiVersion: v2
name: pokemon-app
description: Helm chart pour d√©ployer l'application Pokemon sur Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - pokemon
  - react
  - nginx
maintainers:
  - name: Nabilou Anoir
