# Service Pokemon App
apiVersion: v1
kind: Service
metadata:
  name: pokemon-app-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pokemon-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "pokemon-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - name: metrics
      port: 9113
      targetPort: metrics
      protocol: TCP
